version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: alekseysuhorukov/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - media:/media
      - static:/static_backend
  frontend:
    env_file: .env
    image: alekseysuhorukov/kittygram_frontend
    command: cp -r /app/build/. /static_frontend/
    volumes:
      - static:/static_frontend
  gateway:
    image: alekseysuhorukov/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - media:/media
      - static:/static
    depends_on:
      - backend
      - frontend
